import scrapy

class Author(scrapy.Item):
  id=scrapy.Field()
  name=scrapy.Field()
  score=scrapy.Field()
  follower_count=scrapy.Field()
  referer=scrapy.Field()

class NovelOfAuthor(scrapy.Item):
  aid=scrapy.Field()
  name=scrapy.Field()
  score=scrapy.Field()
  follower_count=scrapy.Field()
  nid=scrapy.Field()
  pub_date=scrapy.Field()

class Novel(scrapy.Item):
  nid=scrapy.Field()
  title=scrapy.Field()
  aid=scrapy.Field()
  author=scrapy.Field()
  intro=scrapy.Field()
  logline=scrapy.Field()
  era=scrapy.Field()
  xx=scrapy.Field()
  yc=scrapy.Field()
  tags=scrapy.Field()
  is_signed=scrapy.Field()
  is_vip=scrapy.Field()
  # is_locked=scrapy.Field()
  word_count=scrapy.Field()
  created=scrapy.Field()
  updated=scrapy.Field()
  chapter_count=scrapy.Field()
  score=scrapy.Field()
  like_count=scrapy.Field()
  style=scrapy.Field()
  ranking=scrapy.Field()
  avg_click=scrapy.Field()
  rating=scrapy.Field()
  copystatus=scrapy.Field()
  comment_count=scrapy.Field()

class NewDayListItem(scrapy.Item):
  rank_date=scrapy.Field(serializer=str)
  vip_date=scrapy.Field(serializer=str)
  rank=scrapy.Field()
  nid=scrapy.Field()
  title=scrapy.Field()
  aid=scrapy.Field()
  author=scrapy.Field()
  era=scrapy.Field()
  yc=scrapy.Field()
  xx=scrapy.Field()
  word_count=scrapy.Field()
  tags=scrapy.Field()
