import scrapy

class Author(scrapy.Item):
  id=scrapy.Field()
  name=scrapy.Field()
  score=scrapy.Field()
  novels=scrapy.Field()
  flw_count=scrapy.Field()

class Novel(scrapy.Item):
  id=scrapy.Field()
  title=scrapy.Field()
  aid=scrapy.Field()
  author=scrapy.Field()
  intro=scrapy.Field()
  genre=scrapy.Field()
  xx=scrapy.Field()
  tags=scrapy.Field()
  is_signed=scrapy.Field()
  is_vip=scrapy.Field()
  is_locked=scrapy.Field()
  word_count=scrapy.Field()
  created=scrapy.Field()
  last_updated=scrapy.Field()
  chpt_count=scrapy.Field()
  score=scrapy.Field()
  flw_count=scrapy.Field()
  style=scrapy.Field()
  ranking=scrapy.Field()
  avg_click=scrapy.Field()
  rating=scrapy.Field()
  copystatus=scrapy.Field()
  comment_count=scrapy.Field()
  comments=scrapy.Field()

class NewDayListItem(scrapy.Item):
  date=scrapy.Field(serializer=str)
  vip_date=scrapy.Field(serializer=str)
  rank=scrapy.Field()
  nid=scrapy.Field()
  title=scrapy.Field()
  aid=scrapy.Field()
  author=scrapy.Field()
  genre=scrapy.Field()
  yc=scrapy.Field()
  xx=scrapy.Field()
  word_count_w=scrapy.Field()
  tags=scrapy.Field()
